# Generated by Django 4.0.5 on 2022-07-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTimeseriesUnadjusted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_symbol', models.CharField(max_length=10)),
                ('stock_open', models.DecimalField(decimal_places=4, max_digits=10)),
                ('stock_high', models.DecimalField(decimal_places=4, max_digits=10)),
                ('stock_low', models.DecimalField(decimal_places=4, max_digits=10)),
                ('stock_close', models.DecimalField(decimal_places=4, max_digits=10)),
                ('stock_volume', models.BigIntegerField()),
                ('cobdate_partition', models.DateField()),
            ],
            options={
                'db_table': 'daily_timeseries_unadjusted',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
    ]
